syntax = "proto3";

package dev.jakubw.omnisentry.proto;

message TransactionDto {
  string internal_id = 1;
  string transaction_id = 2;
  string account_id = 3;
  double amount = 4;
  string currency = 5;
  string description = 6;
  string category = 7;
  string made_on = 8;
  string status = 9;
}

message HistoryRequest{
  string customer_id = 1;
  string connection_id = 2;
  int32 months_limit = 3;
}

message TransactionList {
  repeated TransactionDto transactions = 1;
}

service AnalyticsDataService {
  rpc GetHistory(HistoryRequest) returns (TransactionList);
}